networks:
  codexray-network:
    name: codexray-network
    driver: bridge

volumes:
  prometheus_data: {}
  clickhouse_data: {}
  clickhouse_logs: {}
  codexray_data: {}
  node_agent_data: {}
  cluster_agent_data: {}
  postgres_data: {}

services:
  codexray:
    container_name: codexray
    restart: always
    image: ghcr.io/codifinary/codexray:latest
    pull_policy: always
    volumes:
      - codexray_data:/data
    ports:
      - 8080:8080
    command:
      - "--data-dir=/data"
      - "--pg-connection-string=postgres://codexray:codexray123@postgres:5432/codexray?sslmode=disable"
      - "--bootstrap-prometheus-url=http://prometheus:9090"
      - "--bootstrap-refresh-interval=15s"
      - "--bootstrap-clickhouse-address=clickhouse:9000"
    depends_on:
      - clickhouse
      - prometheus
      - postgres
    networks:
      - codexray-network

  node-agent:
    container_name: codexray-node-agent
    restart: always
    image: ghcr.io/codifinary/codexray-node-agent:latest
    pull_policy: always
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - node_agent_data:/data
    command:
      - "--collector-endpoint=http://codexray:8080"
      - "--cgroupfs-root=/host/sys/fs/cgroup"
      - "--wal-dir=/data"
    networks:
      - codexray-network

  prometheus:
    container_name: codexray-prometheus
    image: prom/prometheus:v3.4.0
    restart: always
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-otlp-receiver"
    ports:
      - "9090:9090"
    networks:
      - codexray-network

  clickhouse:
    container_name: codexray-clickhouse
    restart: always
    image: clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=vizares
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ports:
      - 8043:9000    
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - codexray-network

  postgres:
    container_name: codexray-postgres
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_DB=codexray
      - POSTGRES_USER=codexray
      - POSTGRES_PASSWORD=codexray123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 8004:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codexray -d codexray"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codexray-network
